
language: python

# For pypy versions, see https://github.com/pyenv/pyenv/tree/master/plugins/python-build/share/python-build
# notice that pypy may or may not work for real: test in CI has small coverage, pyglet and cocos uses ctypes,
# cocos particles and audio SDL uses numpy (ctypes and numpy are problematic with pypy)
# py3 should be tested only on CPython versions actively supported, meaning receiving security updates, look
# at https://docs.python.org/devguide/#status-of-python-branches for status

# Travis refs
# https://docs.travis-ci.com/user/languages/python/
# https://docs.travis-ci.com/user/languages/python/#pypy-support


python: 
#  - "pypy2" does not work; with a finer spec works
  - "pypy2.7-7.1.1"
  - "pypy3"
#  - "pypy3.6-v7.1.1" finer spec don't work
  - 2.7
  - 3.4
  - 3.6
  - 3.7
  
cache:
  - pip
  - directories:
    - $HOME/.pyenv_cache

env:
  - cocos_utest=1

install:
   - python setup.py install
script:
- cd utest && py.test --tb native
